{
 "title": "Jenkins Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Folder",
    "label": "folder",
    "query": "SHOW TAG VALUES FROM job WITH KEY = \"owner\""
   },
   {
    "name": "job",
    "label": "Job",
    "query": "SHOW TAG VALUES FROM job WITH KEY = repo WHERE \"owner\" =~ /$Folder/"
   }
  ]
 },
 "panels": [
  {
   "title": "Jenkins Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"56.228.17.205:8080\", job=\"jenkins\"}"
    }
   ]
  },
  {
   "title": "Executor Count, Node Count & Queue Size ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "jenkins_executor_count_value{instance=\"56.228.17.205:8080\", job=\"jenkins\"}\t",
     "legendFormat": "Executor Count"
    },
    {
     "expr": "jenkins_node_count_value{instance=\"56.228.17.205:8080\", job=\"jenkins\"}",
     "legendFormat": "Node Count"
    },
    {
     "expr": "jenkins_queue_size_value{instance=\"56.228.17.205:8080\", job=\"jenkins\"}\t",
     "legendFormat": "Queue Size"
    }
   ]
  },
  {
   "title": "OVERALL BUILDS",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Success",
     "query": "SELECT count(build_number) FROM \"jenkins_data\" WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$Folder.*$/) AND (\"build_result\" = 'SUCCESS' OR \"build_result\" = 'CompletedSuccess' ) AND $timeFilter \n"
    },
    {
     "alias": "Failure",
     "query": "SELECT count(build_number) FROM \"jenkins_data\" WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$Folder.*$/) AND (\"build_result\" = 'FAILURE' OR \"build_result\" = 'CompletedError' ) AND $timeFilter "
    },
    {
     "alias": "Aborted",
     "query": "SELECT count(build_number) FROM \"jenkins_data\" WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$Folder.*$/) AND (\"build_result\" = 'ABORTED' OR \"build_result\" = 'Aborted' ) AND $timeFilter "
    },
    {
     "alias": "Unstable",
     "query": "SELECT count(build_number) FROM \"jenkins_data\" WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$Folder.*$/) AND (\"build_result\" = 'UNSTABLE' OR \"build_result\" = 'Unstable' ) AND $timeFilter "
    }
   ]
  },
  {
   "title": "Number of pipelines ran",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select count(DISTINCT project_name) FROM jenkins_data WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$Folder.*$/) AND $timeFilter "
    }
   ]
  },
  {
   "title": "Average Build Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Average Build Time",
     "query": "select build_time/1000 FROM jenkins_data WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$Folder.*$/) AND $timeFilter "
    }
   ]
  },
  {
   "title": "Number of Builds Ran",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(build_number) FROM \"jenkins_data\" WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$Folder.*$/) AND $timeFilter "
    }
   ]
  },
  {
   "title": "Latest Build Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "grad" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Build Status",
     "query": "SELECT build_result FROM \"jenkins_data\" WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$Folder.*$/) AND $timeFilter  ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Build Details",
   "type": "table",
   "description": "Show all the recent builds",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "SELECT \"build_exec_time\",\"project_path\",\"build_number\",\"build_causer\",\"build_time\",\"build_result\" FROM \"jenkins_data\" WHERE (\"project_name\" =~ /^(?i)$job$/ AND \"project_path\" =~ /.*(?i)$Folder.*$/) AND $timeFilter "
    }
   ]
  },
  {
   "title": "All Active Plugins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_plugins_active{instance=\"56.228.17.205:8080\", job=\"jenkins\"}\t"
    }
   ]
  },
  {
   "title": "Inactive Plugins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_plugins_inactive" }
   ]
  },
  {
   "title": "Plugins wirh Update",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_plugins_withUpdate" }
   ]
  },
  {
   "title": "Failed Plugins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_plugins_failed{instance=\"56.228.17.205:8080\", job=\"jenkins\"}\t"
    }
   ]
  }
 ]
}